- hosts: nautilus_app2
  gather_facts: false
  become: true

  vars:
    dns_file: /etc/resolv.conf

  tasks:
    - name: Change to Google DNS
      lineinfile:
        path: "{{ dns_file }}"
        regexp: '^nameserver'
        line: nameserver 8.8.8.8
        unsafe_writes: true
