apiVersion: v1
kind: ConfigMap
metadata:
  name: php-config
data:
  php.ini: |
    upload_max_filesize = 64M
    post_max_size = 64M
    memory_limit = 256M
    max_execution_time = 60
    max_input_time = 60
