apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3M=  
  MYSQL_DATABASE: d29yZHByZXNz    
  MYSQL_USER: d3B1c2Vy          
  MYSQL_PASSWORD: d3BwYXNz      
  MYSQL_HOST: bXlzcWwtc2VydmljZQ==  # base64-encoded 'mysql-service'
