apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ic-xfusion
  name: ic-deploy-xfusion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-xfusion
  template:
    metadata:
      labels:
        app: ic-xfusion
    spec:
      initContainers:
      - name: ic-msg-xfusion
        image: fedora:latest
        command: ["/bin/bash", "-c", "echo Init Done - Welcome to xFusionCorp Industries > /ic/blog"]
        volumeMounts:
        - name: ic-volume-xfusion
          mountPath: /ic

      containers:
      - name: ic-main-xfusion
        image: fedora:latest
        command: ["/bin/bash", "-c", "while true; do cat /ic/blog; sleep 5; done"]
        volumeMounts:
        - name: ic-volume-xfusion
          mountPath: /ic
        ports:
        - containerPort: 80

      volumes:
      - name: ic-volume-xfusion
        emptyDir: {}