apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  ports:
  - name: nginx-service
    port: 80          # Service port (external)
    targetPort: 80    # Container port
    nodePort: 30011   # Specific NodePort
    protocol: TCP
  selector:
    app: nginx