- hosts: nautilus_apps
  gather_facts: false
  become: true

  vars:
    sshd_config: /etc/ssh/sshd_config

  tasks:
    - name: Disable SSH login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin yes'
        line: PermitRootLogin no
    - name: Restart SSH service
      service:
        name: sshd
        state: restarted