- hosts: nautilus_apps_db
  gather_facts: false
  become: true

  vars:
    src_file: /home/thor/nautilus_banner

  tasks:
    - name: Update message of the day
      copy:
        src: "{{ src_file }}"
        dest: /etc/motd