- hosts: nautilus_db_server
  gather_facts: false
  become: true

  tasks:
    - name: Initialize MySQL
      shell: "mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql"
    - name: Start mariadb service
      service:
        name: mariadb
        state: started
    - systemd:
        name: mariadb
      register: mariadb_service_status
    - name: Check mariadb service is running
      assert:
        that: "'active' in mariadb_service_status.status.ActiveState"