- hosts: nautilus_app1
  gather_facts: false
  become: true

  vars:
    user: mariyam
    src_dir: /home/usersdata/
    dest_dir: /media

  tasks:
    - name: Move all files owned by {{ user }} to {{ dest_dir }}
      shell: "find {{ src_dir }} -type f -user {{ user }} -exec cp --parents {} {{ dest_dir }} \\;"