- hosts: nautilus_app2
  gather_facts: false
  become: true

  vars:
    group: sysops
    dir: /sysops
    sub_dir: /data

  tasks:
    - name: create user {{ group }}
      user:
        name: "{{ group }}"
        group: "{{ group }}"
    - name: create group {{ group }}
      group:
        name: "{{ group }}"
        state: present
    - name: create {{ dir }}
      file:
        path: "{{ dir }}"
        state: directory
        mode: "0770"
        owner: "{{ group }}"
        group: "{{ group }}"
    - name: create {{ dir }}{{ sub_dir }}
      file:
        path: "{{ dir }}{{ sub_dir }}"
        state: directory
        mode: "0770"
        owner: "{{ group }}"
        group: "{{ group }}"
