apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000         # Port on the service
      targetPort: 3000    # Port in the Grafana container
      nodePort: 32000     # External port to access Grafana
