apiVersion: v1
kind: Pod
metadata:
  name: secret-nautilus
spec:
  containers:
    - name: secret-container-nautilus
      image: debian:latest
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: secret-volume
          mountPath: /opt/demo  # Secret will be mounted here
  volumes:
    - name: secret-volume
      secret:
        secretName: ecommerce  # Name of the Secret created earlier
  restartPolicy: Always