apiVersion: v1
kind: Pod
metadata:
  name: pod-datacenter
spec:
  containers:
  - name: container-datacenter
    image: httpd:latest
    volumeMounts:
    - name: storage-volume
      mountPath: /usr/local/apache2/htdocs
  volumes:
  - name: storage-volume
    persistentVolumeClaim:
      claimName: pvc-datacenter