apiVersion: v1
kind: Service
metadata:
  name: web-datacenter
spec:
  selector:
    app: pod-datacenter  # Ensure this matches the Pod label if applicable
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
